# For auto-regressive models
encoder_n: 1
prefill_n: 1
decode_n: 1
encoder_len: 1
prefill_len: 1
decode_len: 6

# For DiffusionPolicy
diffusion_step: 100
diffusion_stage_num: 5

input_img_num: 4       #[1, 2, 4]
input_img_size: 84     #[96, 84, 84]
input_traj_cnn_size: 16
input_traj_transformer_size: 10
input_cond_size: 274   #[66, 137, 274]
input_dim: 20          #[2, 10, 20]

# For DiffusionPolicy model
cond_dim: 274          #[66, 137, 274]
n_emb: 768             #[256, 256, 768]
global_cond_dim: 548   #[132, 274, 548]

# For scaling
perception_scale: 0.5
generation_scale: 0.5

simu_ts_len: 500
real_run: True
mode: "seq"
profile_mode: "flashinfer"
verbose: 0

req_interval: 0.1362
worker_num: 3
query_interval: 1
model: "diffusion_transformer"
enable_slice: False

trail_num: 20
warmup_num: 10
