# For auto-regressive models
encoder_n: 1
prefill_n: 1
decode_n: 1
encoder_len: 1
prefill_len: 1
decode_len: 10

# For DiffusionPolicy
diffusion_step: 100
diffusion_stage_num: 5

simu_ts_len: 500
real_run: True
mode: "parallel_v2"
profile_mode: "flashinfer"
verbose: 0

req_interval: 0.06978000
worker_num: 4
query_interval: 1
model: "llava"
enable_slice: False

trail_num: 20
warmup_num: 10
